version: '3.8'
services:
  app_mysql:
    image: mysql:latest
    ports:
      - 7000:3306
    environment:
      - MYSQL_ROOT_PASSWORD=leandro123
    container_name: app_mysql
    networks:
      - my-network

  app_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_php
    ports:
      - 8080:80
    networks:
      - my-network

networks:
  my-network:
